import Header from '@/components/Header/Header';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Modal from '@/components/Modal/Modal';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Risk of rain 2 Wiki',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Modal itemTitle="some" changeModalState={setModalState} modalState={modalState} /> */}
        <Header />
        {children}
      </body>
    </html>
  );
}
